### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by freemer** [neoxia/is-workspace-affected#366]
It seems like the 1.0 version of this action will cease working on 31st May 2023:
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```

The PR to bump `@actions/core` has been merged to `master`, and pointing to the commit makes the warning go away, so a new release will sort this out.

**Comment by julien-capellari** [comment]
Hello @freemer !

You're right, I forgot to tag it. It's done now you can use the v2 ([release notes](https://github.com/neoxia/is-workspace-affected/releases/tag/v2.0.0)).
